vich_uploader:
    db_driver: orm

    mappings:
        cover_image:
            uri_prefix: /images/covers
            upload_destination: '%kernel.project_dir%/public/images/covers'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
